### ISSUE TITLE
AttributeError: module 'shlex' has no attribute 'join'

### ISSUE THREAD

**Issue by MobileAnalytics** [ColdGrub1384/fortran-ios#1]
Hello, I encountered following error when compiling f code, the gfortran was downloaded from your repo, my OS is macOS Big Sur, how to fix?

./gfortran -arch arm64 -c ./helloworld.f -o helloworld.o
Traceback (most recent call last):
  File "./gfortran", line 97, in <module>
    flang_command = shlex.join(arguments)
AttributeError: module 'shlex' has no attribute 'join'

**Comment by ColdGrub1384** [comment]
Hi. The `join` function was introduced in Python 3.8: https://docs.python.org/3/library/shlex.html#shlex.join. I didn't know it didn't work in previous versions because I just used Python 3.8. I'll update the code to work on previous versions.

**Comment by ColdGrub1384** [comment]
I released a new build that should now work: https://github.com/ColdGrub1384/fortran-ios/releases/tag/v1.1
